### ISSUE TITLE
Question is there any comparison to plugins written in lua (which is "native" to nginx)?

### ISSUE THREAD

**Issue by tomer-ben-david** [taoensso/clojure-web-benchmarks#31]

**Comment by xfeep** [comment]
@tomer-ben-david 
Hi, I just did a very, very simple benchmark with nginx lua module and nginx-clojure. They are very close at speed and nginx lua used much less memory because JVM needs cache java class code and a lot of build-in java objects. Because both of them use nginx native c code to handle network I/O so I think this simple benchmark,  viz.  with **only one** nginx worker and simple default configurations ,maybe is enough.

The results  are here :
1. nginx-clojure java handler :  `90k` reqs/s, Mem `119M`, after GC: JVM heap used `12M`, others were free , (jvm option `-Xms256m -Xmx256m`)
2. nginx-clojure clojure handler : `87k` reqs/s, Mem `128M`, after GC: JVM heap used `18M`, others were free,  (jvm option `-Xms256m -Xmx256m`)
3. nginx lua : `81k` reqs/s, Mem `1M`

More details about this simple benchmark :

0. OS ubuntu 14.04, jdk 1.7.0_45, cpu i7-4700, RAM 16G
1. wrk 4.0, 1000 connections, 4 threads. 10s,  all servers got warmup, testing commands
  
  ```shell
  #nginx-clojure java handler
  wrk -t 4 -c 1000 -d 10s  http://localhost:8081/hello
  #nginx lua
  wrk -t 4 -c 1000 -d 10s  http://localhost:8082/hello
  #nginx-clojure clojure handler
  wrk -t 4 -c 1000 -d 10s  http://localhost:8083/hello
  ```
1. nginx lua module from openresty-1.7.10.2rc1, nginx-clojure 0.4.0 with nginx 1.8.0
3. nginx.conf & sources
  
  nginx.conf
  ```nginx
worker_processes  1;
error_log  logs/error.log;
events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    access_log off;
    keepalive_timeout  65;
   .....
}
```
nginx lua script 
```lua
    location /hello {
         content_by_lua "
            body = 'Hello, Nginx!'
            ngx.header['Content-Length'] = #body
            ngx.header['Content-Type'] = 'text/plain';
            ngx.print(body)
         ";
       }
  ```
nginx-clojure java handler
```nginx
       location /hello {
         content_handler_type java;
         content_handler_name 'my.HelloHandler';
       }
```
```java
package my;


import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import nginx.clojure.java.NginxJavaRingHandler;

public class HelloHandler implements NginxJavaRingHandler {
	
	@Override
	public Object[] invoke(Map<String, Object> request) throws IOException {
		Map<String, String> headers = new HashMap<String, String>(1);
		headers.put("Content-Type", "text/plain");
		return new Object[] { 
				200, //http status 200
				headers,
				"Hello, Nginx!"  //response body can be string, File or Array/Collection of string or File
				};
	}
}
```

nginx-clojure clojure handler

```clojure
       location /hello {
         content_handler_type clojure;
         content_handler_code '
           (fn[r] {:status 200 :headers {"Content-Type" "text/plain"} :body "Hello, Nginx!"})
         ';
       }
```

**Comment by xfeep** [comment]
Further more, if we use below configuration for nginx-clojure
```nginx
    jvm_options "-Xms16m";
    jvm_options "-Xmx16m";
    #thread stack size, x64 linux JDK at least use 228k thread stack
    jvm_options "-Xss228k"; 
```
The jvm will use less memory under the same benchmark without loss of performance.
1. nginx-clojure java handler : 90k reqs/s, Mem 30M, after GC: JVM heap used 1.5M, others were free , 
2. nginx-clojure clojure handler : 87k reqs/s, Mem 47M, after GC: JVM heap used 6M, others were free,

**Comment by ptaoussanis** [comment]
Closing as part of issue triage, looks like this question was hopefully addressed
